## Numpy Fundamentals for Data Analytics

In [6]:
#!pip install numpy
import numpy

In [2]:
#Creating an array
list1 = [1, 5, 7, 8,0, 9, -2]
a = numpy.array(list1)
print(a)
print(type(a))

[ 1  5  7  8  0  9 -2]
<class 'numpy.ndarray'>


In [3]:
a1 = numpy.array([1, 2, 3, 8, 0, 5, -4, 1])
print(a1)

[ 1  2  3  8  0  5 -4  1]


In [4]:
a2 = numpy.array([[1, 0, 9], 
                  [3, 4, 7],
                  [-1, 0, 5]])
print(a2)

[[ 1  0  9]
 [ 3  4  7]
 [-1  0  5]]


In [8]:
import numpy as np

In [9]:
a3 = np.array([0, 9, 3])
a3

array([0, 9, 3])

In [10]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [11]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
np.arange(0, 11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [14]:
np.linspace(0, 1, 4)

array([0.        , 0.33333333, 0.66666667, 1.        ])

In [15]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [16]:
np.linspace(0, 100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [17]:
sales = np.array([1200, 1500, 900, 1800, 1600])
print("Sales:", sales)

Sales: [1200 1500  900 1800 1600]


In [109]:
store_sales = np.array([[1200, 2500, 900],
                       [1800, 1600, 1700]])
store_sales

array([[1200, 2500,  900],
       [1800, 1600, 1700]])

In [21]:
print("Data type of sales:", sales.dtype)

Data type of sales: int64


In [24]:
sls = [1200, 1500, 900, 1800, 1600]
sales_float = np.array(sls, dtype = 'float64')
sales_float

array([1200., 1500.,  900., 1800., 1600.])

In [25]:
sales_int = sales_float.astype('int32')
sales_int

array([1200, 1500,  900, 1800, 1600], dtype=int32)

### Indexing and Slicing

In [29]:
#first element
sales[0]

np.int64(1200)

In [28]:
#last element
sales[-1]

np.int64(1600)

In [30]:
store_sales

array([[1200, 1500,  900],
       [1800, 1600, 1700]])

In [31]:
store_sales[0, 1]

np.int64(1500)

In [32]:
store_sales[1, 2]

np.int64(1700)

In [33]:
store_sales[:, 1:2]

array([[1500],
       [1600]])

In [34]:
store_sales[:, 1:]

array([[1500,  900],
       [1600, 1700]])

In [37]:
a4 = np.arange(20).reshape(4, 5)
a4

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [38]:
a4[1:3, 2:]

array([[ 7,  8,  9],
       [12, 13, 14]])

In [ ]:
a4[1:,1:4]

In [39]:
a4[:, 1]

array([ 1,  6, 11, 16])

In [41]:
a4[2, :]

array([10, 11, 12, 13, 14])

## Shape and Reshape

In [42]:
print("Shape of Sales array:", sales.shape)

Shape of Sales array: (5,)


In [43]:
print("Shape of Sales array:", store_sales.shape)

Shape of Sales array: (2, 3)


In [44]:
data = np.array([1, 2,3, 4, 5, 6])
data

array([1, 2, 3, 4, 5, 6])

In [56]:
data.size # number of elements

6

In [45]:
data.shape

(6,)

In [57]:
data2 = data.reshape(2, 3)

In [50]:
data2

array([[1, 2, 3],
       [4, 5, 6]])

In [51]:
data3 = data.reshape(3, 2)
data3

array([[1, 2],
       [3, 4],
       [5, 6]])

In [58]:
data3.size

6

In [52]:
flattened_array = data3.reshape(-1)  # 1-d array
flattened_array

array([1, 2, 3, 4, 5, 6])

In [61]:
aa = data.reshape(3, 2)

In [62]:
aa

array([[1, 2],
       [3, 4],
       [5, 6]])

In [63]:
a4.reshape(-1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [64]:
a4.size

20

In [65]:
a4.reshape(2, 10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [66]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a + b)    ## add
print(a - b)    ## subtract
print(a * b)    ## multiply
print(a / b)   ## divide

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


### Iterating through arrays

In [67]:
sales

array([1200, 1500,  900, 1800, 1600])

In [68]:
for value in sales:
    print(value)

1200
1500
900
1800
1600


In [69]:
store_sales

array([[1200, 1500,  900],
       [1800, 1600, 1700]])

In [70]:
for value in store_sales:
    print(value)

[1200 1500  900]
[1800 1600 1700]


In [71]:
for elements in np.nditer(store_sales):
    print(elements)

1200
1500
900
1800
1600
1700


### Join, Split, Sort and Filter

In [74]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

combined = np.concatenate((a, b))
combined

array([1, 2, 3, 4, 5, 6])

In [75]:
combined = np.concatenate((b, a))
combined

array([4, 5, 6, 1, 2, 3])

In [77]:
split_data = np.array_split(combined, 3)
split_data

[array([4, 5]), array([6, 1]), array([2, 3])]

In [78]:
split_data = np.array_split(combined, 2)
split_data

[array([4, 5, 6]), array([1, 2, 3])]

In [79]:
split_data = np.array_split(combined, 6)
split_data

[array([4]), array([5]), array([6]), array([1]), array([2]), array([3])]

In [80]:
#search

sales

array([1200, 1500,  900, 1800, 1600])

In [82]:
indices  = np.where(sales > 1400)
print(indices)

(array([1, 3, 4]),)


In [93]:
sales[indices]

array([1500, 1800, 1600])

In [83]:
a4

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [87]:
np.array_split(a4, 3)

[array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]),
 array([[10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19]])]

In [88]:
a6 = np.arange(20)
a6

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [89]:
np.array_split(a6, 3)

[array([0, 1, 2, 3, 4, 5, 6]),
 array([ 7,  8,  9, 10, 11, 12, 13]),
 array([14, 15, 16, 17, 18, 19])]

In [97]:
#sorting

sorted_sales = np.sort(sales)
sorted_sales

array([ 900, 1200, 1500, 1600, 1800])

In [95]:
sales

array([1200, 1500,  900, 1800, 1600])

In [100]:
np.sort(store_sales)

array([[ 900, 1200, 1500],
       [1600, 1700, 1800]])

In [101]:
sales[sales>1400]

array([1500, 1800, 1600])

In [110]:
store_sales

array([[1200, 2500,  900],
       [1800, 1600, 1700]])

In [111]:
np.sort(store_sales, axis = 0)

array([[1200, 1600,  900],
       [1800, 2500, 1700]])

In [112]:
np.sort(store_sales, axis = 1)

array([[ 900, 1200, 2500],
       [1600, 1700, 1800]])

In [113]:
a7 = np.arange(20).reshape(2, 5, 2)
a7

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [117]:
np.sort(sales)[::-1]

array([1800, 1600, 1500, 1200,  900])

In [119]:
np.sort(store_sales)[::]

array([[ 900, 1200, 2500],
       [1600, 1700, 1800]])

In [130]:
np.random.seed(10)
np.random.rand(3)

array([0.77132064, 0.02075195, 0.63364823])

In [124]:
np.random.randn(3)

array([-0.18400732,  0.52239737,  0.43517906])

In [126]:
np.random.poisson(3, 5)

array([3, 1, 1, 2, 6], dtype=int32)